# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      # specify the version
      - image: circleci/golang:1.9
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    #### TEMPLATE_NOTE: go expects specific checkout path representing url
    #### expecting it in the form of
    ####   /go/src/github.com/circleci/go-tool
    ####   /go/src/bitbucket.org/circleci/go-tool
    working_directory: /go/src/github.com/ubports/ubuntu-push
    steps:
      - checkout

      # specify any bash command here prefixed with `run:
      - run: apt install build-essential cmake libdbus-1-dev libgcrypt11-dev libglib2.0-dev libnih-dbus-dev libsqlite3-dev libubuntuoneauth-2.0-dev libmessaging-menu-dev libubuntu-app-launch2-dev libclick-0.4-dev liburl-dispatcher1-dev libaccounts-glib-dev system-image-dbus
      - run: make fetchdeps
      - run: make bootstrap
      - run: make check
